# Generated by Django 2.1.2 on 2019-04-28 07:20

import advertisement.models
import advertisement.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default=advertisement.utils.generate_random_token, max_length=32)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Advertiser')),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='profile_image',
            field=models.ImageField(default='../static/default.jpg', upload_to=advertisement.models.get_image_path),
        ),
    ]
