# Generated by Django 2.1.2 on 2019-05-18 15:31

import advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='profile_image',
            field=models.ImageField(default='../static/default.jpg', upload_to=advertisement.models.get_image_path),
        ),
    ]
