# Generated by Django 2.1.2 on 2019-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_advertisement_immediate'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='favorite_ads',
            field=models.ManyToManyField(related_name='interested_advertiser', to='advertisement.Advertisement'),
        ),
    ]
