# Generated by Django 2.1.2 on 2019-05-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_auto_20190515_1011'),
        ('advertisement', '0002_auto_20190518_1531'),
    ]

    operations = [
    ]
